### ISSUE TITLE
@conda-forge-admin, please rerender

### ISSUE THREAD

**Issue by knaaptime** [conda-forge/pysal-feedstock#46]

**Comment by martinfleis** [comment]
There's no need for these. Re-rendering happens automatically in the update PR.

**Comment by martinfleis** [comment]
It is unlikely that we would need to re-render manually at all.

**Comment by knaaptime** [comment]
got it, thanks. i was hpoing something in the re-render would change the infrastructure so that when it looks at pip, the pins get updated (so I was seeing if rendering prior to generating the PR would fix things)

...clearly not
