### ISSUE TITLE
An error occurred while installing package

### ISSUE THREAD

**Issue by fmaussion** [conda-forge/pysal-feedstock#7]
Hi,

A strange error started to hit our ReadTheDocs builds about five days ago: https://readthedocs.org/projects/oggm/builds/6020040/

The log is ugly but here is the relevant part:

```
ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'conda-forge::pysal-1.14.2-py_0'.
CalledProcessError()
Attempting to roll back.



CalledProcessError()
```

Any idea about what's going on? Thanks!

**Comment by ocefpaf** [comment]
See #8 and the fix in #9
